// src/components/Cards.vue
<template>
  <div class="space-y-4">
    <div class="scanner-card-frame rounded-lg bg-scanner-panel border border-scanner p-3">
      <form role="search" class="flex gap-2" @submit.prevent="executeSearch">
        <label class="input input-bordered flex-1 flex items-center gap-2 bg-scanner-card border-scanner font-mono text-sm">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 text-cyan-500/50" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
          </svg>
          <input
            id="search-input"
            type="text"
            class="grow bg-transparent placeholder:text-scanner-dim/40"
            placeholder="SEARCH DATABASE..."
            v-model="searchInput"
            :disabled="loading"
            aria-label="Search cards by name"
          />
        </label>
        <button 
          type="submit"
          class="btn btn-sm btn-square bg-cyan-500/10 border border-cyan-500/30 text-cyan-600 dark:text-cyan-400 hover:bg-cyan-500/20 hover:border-cyan-500/50 active:scale-95 transition-transform" 
          :disabled="loading"
          aria-label="Search"
        >
          <span v-if="loading" class="loading loading-spinner loading-xs text-cyan-500"></span>
          <svg v-else xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
          </svg>
        </button>
        <button 
          type="button" 
          class="btn btn-sm btn-square bg-scanner-card border border-scanner text-scanner-dim hover:border-cyan-500/30 hover:text-cyan-500 active:scale-95 transition-transform"
          :class="{ 'border-cyan-500/50 text-cyan-500': activeSwitch }"
          @click.stop="toggleFilters()" 
          :aria-label="activeSwitch ? 'Close filters' : 'Open filters'"
          :aria-expanded="activeSwitch"
        >
          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4" />
          </svg>
        </button>
      </form>
    </div>

    <Transition name="filter-panel">
      <div v-if="activeSwitch" class="bg-scanner-panel border border-scanner rounded-lg p-4 mt-3">
        <form class="space-y-4" @submit.prevent="executeAdvancedSearch">
          <div class="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
            <label for="filter-archetype" class="sm:w-48 text-sm font-medium text-scanner-dim shrink-0">Archetypes</label>
            <select id="filter-archetype" class="select select-bordered flex-1 bg-scanner-card border-scanner text-scanner" v-model="advance.archetype" :disabled="disabledInputNotMonster">
              <option value="">ALL</option>
              <option v-for="(archetype, a) in archetypes" :key="a" :value="archetype">{{ archetype }}</option>
            </select>
          </div>

          <div class="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
            <label class="sm:w-48 text-sm font-medium text-scanner-dim shrink-0">Race Card</label>
            <div class="flex-1 flex gap-3">
              <select id="filter-race-card" class="select select-bordered flex-1 bg-scanner-card border-scanner text-scanner" v-model="racecard">
                <option :value="null">ALL</option>
                <option v-for="(race, i) in races" :key="i" :value="race.toLowerCase()">{{ race }}</option>
              </select>
              <select id="filter-race-option" class="select select-bordered flex-1 bg-scanner-card border-scanner text-scanner" v-model="advance.race" :disabled="!racecard">
                <option value="">ALL</option>
                <option v-for="(option, j) in raceOptionsValue" :key="j" :value="option">{{ option }}</option>
              </select>
            </div>
          </div>

          <div class="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
            <label for="filter-attribute" class="sm:w-48 text-sm font-medium text-scanner-dim shrink-0">Attribute</label>
            <select id="filter-attribute" class="select select-bordered flex-1 bg-scanner-card border-scanner text-scanner" v-model="advance.attribute" :disabled="disabledInputNotMonster">
              <option value="">ALL</option>
              <option>Earth</option>
              <option>Water</option>
              <option>Fire</option>
              <option>Wind</option>
              <option>Light</option>
              <option>Dark</option>
              <option>Divine</option>
            </select>
          </div>

          <div class="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
            <label for="filter-type" class="sm:w-48 text-sm font-medium text-scanner-dim shrink-0">Type</label>
            <select id="filter-type" class="select select-bordered flex-1 bg-scanner-card border-scanner text-scanner" v-model="advance.type" :disabled="disabledInputNotMonster">
              <option value="">ALL</option>
              <option v-for="(type, t) in types" :key="t" :value="type">{{ type }}</option>
            </select>
          </div>

          <div class="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
            <label for="filter-atk-op" class="sm:w-48 text-sm font-medium text-scanner-dim shrink-0">ATK</label>
            <div class="flex-1 flex gap-3">
              <select id="filter-atk-op" class="select select-bordered w-24 bg-scanner-card border-scanner text-scanner" v-model="operator.signe_atk" :disabled="disabledInputNotMonster">
                <option value="=">=</option>
                <option value="lt">&lt;</option>
                <option value="lte">&lt;=</option>
                <option value="gt">&gt;</option>
                <option value="gte">&gt;=</option>
              </select>
              <input id="filter-atk-val" type="number" class="input input-bordered flex-1 bg-scanner-card border-scanner text-scanner" min="0" max="5000" v-model="operator.atk" :disabled="disabledInputNotMonster" />
            </div>
          </div>

          <div class="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
            <label for="filter-def-op" class="sm:w-48 text-sm font-medium text-scanner-dim shrink-0">DEF</label>
            <div class="flex-1 flex gap-3">
              <select id="filter-def-op" class="select select-bordered w-24 bg-scanner-card border-scanner text-scanner" v-model="operator.signe_def" :disabled="disabledInputNotMonster">
                <option value="=">=</option>
                <option value="lt">&lt;</option>
                <option value="lte">&lt;=</option>
                <option value="gt">&gt;</option>
                <option value="gte">&gt;=</option>
              </select>
              <input id="filter-def-val" type="number" class="input input-bordered flex-1 bg-scanner-card border-scanner text-scanner" min="0" max="5000" v-model="operator.def" :disabled="disabledInputNotMonster" />
            </div>
          </div>

          <div class="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
            <label for="filter-level-op" class="sm:w-48 text-sm font-medium text-scanner-dim shrink-0">Level/Rank</label>
            <div class="flex-1 flex gap-3">
              <select id="filter-level-op" class="select select-bordered w-24 bg-scanner-card border-scanner text-scanner" v-model="operator.signe_level" :disabled="disabledInputNotMonster">
                <option value="=">=</option>
                <option value="lt">&lt;</option>
                <option value="lte">&lt;=</option>
                <option value="gt">&gt;</option>
                <option value="gte">&gt;=</option>
              </select>
              <input id="filter-level-val" type="number" class="input input-bordered flex-1 bg-scanner-card border-scanner text-scanner" min="0" max="13" v-model="operator.level" :disabled="disabledInputNotMonster" />
            </div>
          </div>

          <div class="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
            <label for="filter-scale-op" class="sm:w-48 text-sm font-medium text-scanner-dim shrink-0">Pendulum Scale</label>
            <div class="flex-1 flex gap-3">
              <select id="filter-scale-op" class="select select-bordered w-24 bg-scanner-card border-scanner text-scanner" v-model="operator.signe_scale" :disabled="disabledInputNotMonster">
                <option value="=">=</option>
                <option value="lt">&lt;</option>
                <option value="lte">&lt;=</option>
                <option value="gt">&gt;</option>
                <option value="gte">&gt;=</option>
              </select>
              <input id="filter-scale-val" type="number" class="input input-bordered flex-1 bg-scanner-card border-scanner text-scanner" min="0" max="13" v-model="operator.scale" :disabled="disabledInputNotMonster" />
            </div>
          </div>

          <div class="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
            <label for="filter-link-op" class="sm:w-48 text-sm font-medium text-scanner-dim shrink-0">Link</label>
            <div class="flex-1 flex gap-3">
              <select id="filter-link-op" class="select select-bordered w-24 bg-scanner-card border-scanner text-scanner" v-model="operator.signe_link" :disabled="disabledInputNotMonster">
                <option value="=">=</option>
                <option value="lt">&lt;</option>
                <option value="lte">&lt;=</option>
                <option value="gt">&gt;</option>
                <option value="gte">&gt;=</option>
              </select>
              <input id="filter-link-val" type="number" class="input input-bordered flex-1 bg-scanner-card border-scanner text-scanner" min="0" max="6" v-model="operator.link" :disabled="disabledInputNotMonster" />
            </div>
          </div>

          <button type="submit" class="btn btn-block bg-primary text-primary-content hover:bg-primary/90 font-medium" :disabled="loading">
            <span v-if="loading" class="loading loading-spinner loading-sm"></span>
            Find matches
          </button>
        </form>
      </div>
    </Transition>
  </div>

  <div class="flex items-center gap-2 py-2">
    <div class="flex-1 h-px bg-scanner"></div>
    <div class="flex items-center gap-1">
      <div class="w-1 h-1 rounded-full bg-cyan-500/40"></div>
      <span class="text-[8px] font-mono text-scanner-dim/40 tracking-widest">RESULTS</span>
      <div class="w-1 h-1 rounded-full bg-cyan-500/40"></div>
    </div>
    <div class="flex-1 h-px bg-scanner"></div>
  </div>

  <div :aria-busy="loading && searched">
    <div v-if="loading && searched && !cards.length" class="scanner-loading-status">
      <div class="scanner-loader">
        <div class="scanner-loader-ring"></div>
        <div class="scanner-loader-ring"></div>
        <div class="scanner-loader-ring"></div>
        <div class="scanner-loader-core"></div>
      </div>
      <span class="scanner-loading-label">SCANNING DATABASE</span>
    </div>

    <div v-if="searched && cards.length" class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-3">
      <template v-for="(card, i) in cards" :key="card.id || i">
        <Card :card="card" />
      </template>
    </div>

    <div v-if="!loading && searched && cards.length === 0" role="alert" class="scanner-card-frame rounded-lg bg-scanner-panel border border-scanner p-6">
      <div class="flex flex-col items-center gap-3">
        <div class="flex gap-1">
          <div class="w-1 h-4 bg-cyan-500/30 rounded signal-bar"></div>
          <div class="w-1 h-4 bg-cyan-500/30 rounded signal-bar"></div>
          <div class="w-1 h-4 bg-cyan-500/30 rounded signal-bar"></div>
          <div class="w-1 h-4 bg-cyan-500/30 rounded signal-bar"></div>
        </div>
        <span class="text-sm font-mono text-scanner-dim/60">NO ENTRIES FOUND</span>
        <span class="text-xs font-mono text-scanner-dim/40">Adjust search parameters and retry</span>
        <button class="btn btn-sm bg-cyan-500/10 border border-cyan-500/30 text-cyan-600 dark:text-cyan-400 hover:bg-cyan-500/20 font-mono text-xs" @click="clearSearch">RESET QUERY</button>
      </div>
    </div>
  </div>

  <div ref="scrollTrigger" class="h-8 flex items-center justify-center">
    <div v-if="loading && hasMore" class="scanner-loading-more">
      <div class="scanner-data-stream">
        <div class="scanner-data-bar"></div>
        <div class="scanner-data-bar"></div>
        <div class="scanner-data-bar"></div>
        <div class="scanner-data-bar"></div>
        <div class="scanner-data-bar"></div>
        <div class="scanner-data-bar"></div>
        <div class="scanner-data-bar"></div>
        <div class="scanner-data-bar"></div>
      </div>
      <span class="scanner-loading-text">LOADING MORE...</span>
    </div>
  </div>

  <div v-if="!hasMore && cards.length > 0" class="flex flex-col items-center gap-2 py-4">
    <div class="flex items-center gap-2">
      <div class="w-1 h-1 rounded-full bg-cyan-500/40"></div>
      <span class="text-xs font-mono text-scanner-dim/40">END OF RESULTS</span>
      <div class="w-1 h-1 rounded-full bg-cyan-500/40"></div>
    </div>
    <span class="text-[10px] font-mono text-scanner-dim/30">{{ cards.length }} OF {{ totalResults }} RECORDS LOADED</span>
  </div>

  <div v-if="error" role="alert" class="scanner-card-frame rounded-lg bg-scanner-panel border border-red-500/30 p-4">
    <div class="flex items-center gap-3">
      <div class="w-2 h-2 rounded-full bg-red-500 pulse-dot"></div>
      <span class="text-sm font-mono text-red-500">SYSTEM ERROR</span>
    </div>
    <p class="text-xs font-mono text-scanner-dim/60 mt-2">{{ error }}</p>
    <button class="btn btn-sm mt-3 bg-red-500/10 border border-red-500/30 text-red-500 hover:bg-red-500/20 font-mono text-xs" @click="retrySearch">RETRY CONNECTION</button>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted, watch } from "vue";
import { useRoute } from "vue-router";
import useArchetypes from "@/composables/useArchetypes";
import useCards from "@/composables/useCards";
import useUrlFilters from "@/composables/useUrlFilters";
import { debounce } from "@/composables/useDebounce";
import Card from "@/components/Card.vue";
import CardSkeleton from "@/components/CardSkeleton.vue";

const route = useRoute();

const {
  search,
  activeSwitch,
  racecard,
  advance,
  operator,
  syncToUrl,
  resetFilters,
  buildSearchParams,
} = useUrlFilters();

const { cards, error, loading, totalResults, hasMore, getCards, loadMore, resetState } = useCards();
const { archetypes, getArchetypes } = useArchetypes();

const searched = ref(false);
const searchInput = ref('');
const scrollTrigger = ref(null);
let observer = null;
let searchTimeout = null;

const races = ['Monster', 'Spell', 'Trap'];

const raceOptions = {
  monster: [
    'Aqua', 'Beast', 'Beast-Warrior', 'Creator-God', 'Cyberse',
    'Dinosaur', 'Divine-Beast', 'Dragon', 'Fairy', 'Fiend',
    'Fish', 'Insect', 'Machine', 'Plant', 'Psychic',
    'Pyro', 'Reptile', 'Rock', 'Sea Serpent', 'Spellcaster',
    'Thunder', 'Warrior', 'Winged Beast', 'Wyrm', 'Zombie',
  ],
  spell: ['Normal', 'Field', 'Equip', 'Continuous', 'Quick-Play', 'Ritual'],
  trap: ['Normal', 'Continuous', 'Counter'],
};

const types = [
  'Effect Monster',
  'Flip Effect Monster',
  'Flip Tuner Effect Monster',
  'Gemini Monster',
  'Normal Monster',
  'Normal Tuner Monster',
  'Pendulum Effect Monster',
  'Pendulum Effect Ritual Monster',
  'Pendulum Flip Effect Monster',
  'Pendulum Normal Monster',
  'Pendulum Tuner Effect Monster',
  'Ritual Effect Monster',
  'Ritual Monster',
  'Spirit Monster',
  'Toon Monster',
  'Tuner Monster',
  'Union Effect Monster',
  'Fusion Monster',
  'Link Monster',
  'Pendulum Effect Fusion Monster',
  'Synchro Monster',
  'Synchro Pendulum Effect Monster',
  'Synchro Tuner Monster',
  'XYZ Monster',
  'XYZ Pendulum Effect Monster',
];

function debouncedExecuteSearch() {
  clearTimeout(searchTimeout);
  searchTimeout = setTimeout(() => {
    search.value = searchInput.value;
    executeSearch();
  }, 500);
}

watch(() => searchInput.value, () => {
  debouncedExecuteSearch();
});

watch(() => route.query, (newQuery, oldQuery) => {
  const queryChanged = newQuery.q !== oldQuery?.q || 
      newQuery.archetype !== oldQuery?.archetype ||
      newQuery.race !== oldQuery?.race ||
      newQuery.attribute !== oldQuery?.attribute ||
      newQuery.type !== oldQuery?.type;
  
  if (queryChanged) {
    searchInput.value = newQuery.q || '';
    resetState();
    searched.value = true;
    const params = buildSearchParams(0);
    getCards(params);
  }
}, { immediate: true });

const disabledInputNotMonster = computed(() => ['spell', 'trap'].includes(racecard.value));
const raceOptionsValue = computed(() => (racecard.value) ? raceOptions[racecard.value] : []);

function executeSearch() {
  clearTimeout(searchTimeout);
  search.value = searchInput.value;
  resetState();
  searched.value = true;
  syncToUrl();
  const params = buildSearchParams(0);
  getCards(params);
}

function executeAdvancedSearch() {
  resetState();
  searched.value = true;
  activeSwitch.value = false;
  syncToUrl();
  const params = buildSearchParams(0);
  getCards(params);
}

function toggleFilters() {
  activeSwitch.value = !activeSwitch.value;
}

function clearSearch() {
  searchInput.value = '';
  search.value = '';
  resetFilters();
  resetState();
  syncToUrl();
  searched.value = false;
}

function retrySearch() {
  const params = buildSearchParams(0);
  if (Object.keys(params).length > 0) {
    getCards(params);
  }
}

onMounted(() => {
  getArchetypes();
  
  observer = new IntersectionObserver(
    (entries) => {
      if (entries[0].isIntersecting && hasMore.value && !loading.value) {
        console.log('[Cards] IntersectionObserver triggered loadMore');
        loadMore(buildSearchParams);
      }
    },
    { rootMargin: '200px' }
  );

  if (scrollTrigger.value) {
    observer.observe(scrollTrigger.value);
  }
});

onUnmounted(() => {
  if (observer) {
    observer.disconnect();
  }
  clearTimeout(searchTimeout);
});
</script>

// src/components/Cards.tsx
import { useState, useCallback, useRef, useEffect } from 'react';
import toast from 'react-hot-toast';
import { useCardFilters } from '@/hooks/useCardFilters';
import { useCards, mapCard } from '@/hooks/useCards';
import { useArchetypes } from '@/hooks/useArchetypes';
import Card from '@/components/Card';

const races = ['Monster', 'Spell', 'Trap'];

const raceOptions: Record<string, string[]> = {
  monster: [
    'Aqua', 'Beast', 'Beast-Warrior', 'Creator-God', 'Cyberse',
    'Dinosaur', 'Divine-Beast', 'Dragon', 'Fairy', 'Fiend',
    'Fish', 'Insect', 'Machine', 'Plant', 'Psychic',
    'Pyro', 'Reptile', 'Rock', 'Sea Serpent', 'Spellcaster',
    'Thunder', 'Warrior', 'Winged Beast', 'Wyrm', 'Zombie',
  ],
  spell: ['Normal', 'Field', 'Equip', 'Continuous', 'Quick-Play', 'Ritual'],
  trap: ['Normal', 'Continuous', 'Counter'],
};

const types = [
  'Effect Monster', 'Flip Effect Monster', 'Flip Tuner Effect Monster',
  'Gemini Monster', 'Normal Monster', 'Normal Tuner Monster',
  'Pendulum Effect Monster', 'Pendulum Effect Ritual Monster',
  'Pendulum Flip Effect Monster', 'Pendulum Normal Monster',
  'Pendulum Tuner Effect Monster', 'Ritual Effect Monster',
  'Ritual Monster', 'Spirit Monster', 'Toon Monster', 'Tuner Monster',
  'Union Effect Monster', 'Fusion Monster', 'Link Monster',
  'Pendulum Effect Fusion Monster', 'Synchro Monster',
  'Synchro Pendulum Effect Monster', 'Synchro Tuner Monster',
  'XYZ Monster', 'XYZ Pendulum Effect Monster',
];

function debounce<T extends (...args: Parameters<T>) => void>(
  fn: T, delay = 500
): (...args: Parameters<T>) => void {
  let timeout: ReturnType<typeof setTimeout>;
  return function (...args: Parameters<T>) {
    clearTimeout(timeout);
    timeout = setTimeout(() => fn(...args), delay);
  };
}

export default function Cards() {
  const { filters, setFilters, buildQueryParams, resetFilters } = useCardFilters();
  const { data: archetypes = [] } = useArchetypes();

  const [searchInput, setSearchInput] = useState(filters.q);
  const [searched, setSearched] = useState(!!filters.q);
  const scrollTrigger = useRef<HTMLDivElement | null>(null);
  const observer = useRef<IntersectionObserver | null>(null);
  const searchTimeout = useRef<ReturnType<typeof setTimeout> | null>(null);

  const queryParams = buildQueryParams();
  const {
    data,
    error,
    fetchNextPage,
    hasNextPage,
    isFetching,
    isFetchingNextPage,
  } = useCards(queryParams, searched);

  // Show toast when there's an error
  useEffect(() => {
    if (error) {
      toast.error(`Error: ${error.message}`, {
        id: 'cards-error',
        duration: 5000,
      });
    }
  }, [error]);

  const cards = data?.pages.flatMap((page) =>
    page.data.map((r) => mapCard(r.attributes, r.id))
  ) ?? [];

  const totalResults = data?.pages[data.pages.length - 1]?.meta.totalItems ?? 0;

  const disabledInputNotMonster = ['spell', 'trap'].includes(filters.race || '');
  const raceOptionsValue = filters.race ? raceOptions[filters.race] || [] : [];

  const initialQueryRef = useRef(filters.q);

  const debouncedSearch = useCallback(
    debounce((value: string) => {
      setFilters({ q: value });
      setSearched(true);
    }, 800),
    [setFilters]
  );

  useEffect(() => {
    // Skip the very first render if there's nothing in the URL
    const isInitialMount = initialQueryRef.current === searchInput;

    if (isInitialMount && searchInput) {
      // User arrived with ?q=X in URL: trigger immediately
      setSearched(true);
      return;
    }

    // Typing or clearing
    if (searchInput) {
      debouncedSearch(searchInput);
    } else {
      setFilters({ q: null });
      setSearched(false);
    }
  }, [searchInput, debouncedSearch]);

  useEffect(() => {
    observer.current = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting && hasNextPage && !isFetchingNextPage && searched) {
          fetchNextPage();
        }
      },
      { rootMargin: '200px' }
    );

    if (scrollTrigger.current) {
      observer.current.observe(scrollTrigger.current);
    }

    return () => {
      if (observer.current) observer.current.disconnect();
      if (searchTimeout.current) clearTimeout(searchTimeout.current);
    };
  }, [hasNextPage, isFetchingNextPage, searched, fetchNextPage]);

  const executeSearch = () => {
    if (searchInput) {
      setFilters({ q: searchInput });
      setSearched(true);
    }
  };

  const executeAdvancedSearch = () => {
    setSearched(true);
    setFilters({ advanced: false });
  };

  const clearSearch = () => {
    setSearchInput('');
    resetFilters();
    setSearched(false);
  };

  return (
    <>
      <div className="space-y-4">
        <div className="scanner-card-frame rounded-lg bg-scanner-panel border border-scanner p-3">
          <form role="search" className="flex gap-2" onSubmit={(e) => { e.preventDefault(); executeSearch(); }}>
            <label className="input input-bordered flex-1 flex items-center gap-2 bg-scanner-card border-scanner font-mono text-sm">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-cyan-500/50" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
              <input
                id="search-input"
                type="text"
                className="grow bg-transparent placeholder:text-scanner-dim/40"
                placeholder="SEARCH DATABASE..."
                value={searchInput}
                onChange={(e) => setSearchInput(e.target.value)}
                disabled={isFetching}
                aria-label="Search cards by name"
              />
            </label>
            <button
              type="submit"
              className="btn btn-sm btn-square bg-cyan-500/10 border border-cyan-500/30 text-cyan-600 dark:text-cyan-400 hover:bg-cyan-500/20 hover:border-cyan-500/50 active:scale-95 transition-transform"
              disabled={isFetching}
              aria-label="Search"
            >
              {isFetching ? (
                <span className="loading loading-spinner loading-xs text-cyan-500"></span>
              ) : (
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                </svg>
              )}
            </button>
            <button
              type="button"
              className={`btn btn-sm btn-square bg-scanner-card border border-scanner text-scanner-dim hover:border-cyan-500/30 hover:text-cyan-500 active:scale-95 transition-transform ${filters.advanced ? 'border-cyan-500/50 text-cyan-500' : ''}`}
              onClick={() => setFilters({ advanced: !filters.advanced })}
              aria-label={filters.advanced ? 'Close filters' : 'Open filters'}
              aria-expanded={filters.advanced}
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4" />
              </svg>
            </button>
          </form>
        </div>

        {filters.advanced && (
          <div className="bg-scanner-panel border border-scanner rounded-lg p-4 mt-3">
            <form className="space-y-4" onSubmit={(e) => { e.preventDefault(); executeAdvancedSearch(); }}>
              <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
                <label htmlFor="filter-archetype" className="sm:w-48 text-sm font-medium text-scanner-dim shrink-0">Archetypes</label>
                <select
                  id="filter-archetype"
                  className="select select-bordered flex-1 bg-scanner-card border-scanner text-scanner"
                  value={filters.archetype}
                  onChange={(e) => setFilters({ archetype: e.target.value })}
                  disabled={disabledInputNotMonster}
                >
                  <option value="">ALL</option>
                  {archetypes.map((archetype, a) => (
                    <option key={a} value={archetype}>{archetype}</option>
                  ))}
                </select>
              </div>

              <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
                <label className="sm:w-48 text-sm font-medium text-scanner-dim shrink-0">Race Card</label>
                <div className="flex-1 flex gap-3">
                  <select
                    id="filter-race-card"
                    className="select select-bordered flex-1 bg-scanner-card border-scanner text-scanner"
                    value={filters.race || ''}
                    onChange={(e) => setFilters({ race: e.target.value || null })}
                  >
                    <option value="">ALL</option>
                    {races.map((race, i) => (
                      <option key={i} value={race.toLowerCase()}>{race}</option>
                    ))}
                  </select>
                  <select
                    id="filter-race-option"
                    className="select select-bordered flex-1 bg-scanner-card border-scanner text-scanner"
                    value={filters.raceOption}
                    onChange={(e) => setFilters({ raceOption: e.target.value })}
                    disabled={!filters.race}
                  >
                    <option value="">ALL</option>
                    {raceOptionsValue.map((option, j) => (
                      <option key={j} value={option}>{option}</option>
                    ))}
                  </select>
                </div>
              </div>

              <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
                <label htmlFor="filter-attribute" className="sm:w-48 text-sm font-medium text-scanner-dim shrink-0">Attribute</label>
                <select
                  id="filter-attribute"
                  className="select select-bordered flex-1 bg-scanner-card border-scanner text-scanner"
                  value={filters.attribute}
                  onChange={(e) => setFilters({ attribute: e.target.value })}
                  disabled={disabledInputNotMonster}
                >
                  <option value="">ALL</option>
                  <option>Earth</option>
                  <option>Water</option>
                  <option>Fire</option>
                  <option>Wind</option>
                  <option>Light</option>
                  <option>Dark</option>
                  <option>Divine</option>
                </select>
              </div>

              <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
                <label htmlFor="filter-type" className="sm:w-48 text-sm font-medium text-scanner-dim shrink-0">Type</label>
                <select
                  id="filter-type"
                  className="select select-bordered flex-1 bg-scanner-card border-scanner text-scanner"
                  value={filters.type}
                  onChange={(e) => setFilters({ type: e.target.value })}
                  disabled={disabledInputNotMonster}
                >
                  <option value="">ALL</option>
                  {types.map((type, t) => (
                    <option key={t} value={type}>{type}</option>
                  ))}
                </select>
              </div>

              <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
                <label htmlFor="filter-atk-op" className="sm:w-48 text-sm font-medium text-scanner-dim shrink-0">ATK</label>
                <div className="flex-1 flex gap-3">
                  <select
                    id="filter-atk-op"
                    className="select select-bordered w-24 bg-scanner-card border-scanner text-scanner"
                    value={filters.atkOp}
                    onChange={(e) => setFilters({ atkOp: e.target.value })}
                    disabled={disabledInputNotMonster}
                  >
                    <option value="=">=</option>
                    <option value="lt">&lt;</option>
                    <option value="lte">&lt;=</option>
                    <option value="gt">&gt;</option>
                    <option value="gte">&gt;=</option>
                  </select>
                  <input
                    id="filter-atk-val"
                    type="number"
                    className="input input-bordered flex-1 bg-scanner-card border-scanner text-scanner"
                    min="0"
                    max="5000"
                    value={filters.atk}
                    onChange={(e) => setFilters({ atk: e.target.value })}
                    disabled={disabledInputNotMonster}
                  />
                </div>
              </div>

              <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
                <label htmlFor="filter-def-op" className="sm:w-48 text-sm font-medium text-scanner-dim shrink-0">DEF</label>
                <div className="flex-1 flex gap-3">
                  <select
                    id="filter-def-op"
                    className="select select-bordered w-24 bg-scanner-card border-scanner text-scanner"
                    value={filters.defOp}
                    onChange={(e) => setFilters({ defOp: e.target.value })}
                    disabled={disabledInputNotMonster}
                  >
                    <option value="=">=</option>
                    <option value="lt">&lt;</option>
                    <option value="lte">&lt;=</option>
                    <option value="gt">&gt;</option>
                    <option value="gte">&gt;=</option>
                  </select>
                  <input
                    id="filter-def-val"
                    type="number"
                    className="input input-bordered flex-1 bg-scanner-card border-scanner text-scanner"
                    min="0"
                    max="5000"
                    value={filters.def}
                    onChange={(e) => setFilters({ def: e.target.value })}
                    disabled={disabledInputNotMonster}
                  />
                </div>
              </div>

              <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
                <label htmlFor="filter-level-op" className="sm:w-48 text-sm font-medium text-scanner-dim shrink-0">Level/Rank</label>
                <div className="flex-1 flex gap-3">
                  <select
                    id="filter-level-op"
                    className="select select-bordered w-24 bg-scanner-card border-scanner text-scanner"
                    value={filters.lvlOp}
                    onChange={(e) => setFilters({ lvlOp: e.target.value })}
                    disabled={disabledInputNotMonster}
                  >
                    <option value="=">=</option>
                    <option value="lt">&lt;</option>
                    <option value="lte">&lt;=</option>
                    <option value="gt">&gt;</option>
                    <option value="gte">&gt;=</option>
                  </select>
                  <input
                    id="filter-level-val"
                    type="number"
                    className="input input-bordered flex-1 bg-scanner-card border-scanner text-scanner"
                    min="0"
                    max="13"
                    value={filters.level}
                    onChange={(e) => setFilters({ level: e.target.value })}
                    disabled={disabledInputNotMonster}
                  />
                </div>
              </div>

              <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
                <label htmlFor="filter-scale-op" className="sm:w-48 text-sm font-medium text-scanner-dim shrink-0">Pendulum Scale</label>
                <div className="flex-1 flex gap-3">
                  <select
                    id="filter-scale-op"
                    className="select select-bordered w-24 bg-scanner-card border-scanner text-scanner"
                    value={filters.scaleOp}
                    onChange={(e) => setFilters({ scaleOp: e.target.value })}
                    disabled={disabledInputNotMonster}
                  >
                    <option value="=">=</option>
                    <option value="lt">&lt;</option>
                    <option value="lte">&lt;=</option>
                    <option value="gt">&gt;</option>
                    <option value="gte">&gt;=</option>
                  </select>
                  <input
                    id="filter-scale-val"
                    type="number"
                    className="input input-bordered flex-1 bg-scanner-card border-scanner text-scanner"
                    min="0"
                    max="13"
                    value={filters.scale}
                    onChange={(e) => setFilters({ scale: e.target.value })}
                    disabled={disabledInputNotMonster}
                  />
                </div>
              </div>

              <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
                <label htmlFor="filter-link-op" className="sm:w-48 text-sm font-medium text-scanner-dim shrink-0">Link</label>
                <div className="flex-1 flex gap-3">
                  <select
                    id="filter-link-op"
                    className="select select-bordered w-24 bg-scanner-card border-scanner text-scanner"
                    value={filters.linkOp}
                    onChange={(e) => setFilters({ linkOp: e.target.value })}
                    disabled={disabledInputNotMonster}
                  >
                    <option value="=">=</option>
                    <option value="lt">&lt;</option>
                    <option value="lte">&lt;=</option>
                    <option value="gt">&gt;</option>
                    <option value="gte">&gt;=</option>
                  </select>
                  <input
                    id="filter-link-val"
                    type="number"
                    className="input input-bordered flex-1 bg-scanner-card border-scanner text-scanner"
                    min="0"
                    max="6"
                    value={filters.link}
                    onChange={(e) => setFilters({ link: e.target.value })}
                    disabled={disabledInputNotMonster}
                  />
                </div>
              </div>

              <button
                type="submit"
                className="btn btn-block bg-primary text-primary-content hover:bg-primary/90 font-medium"
                disabled={isFetching}
              >
                {isFetching ? (
                  <span className="loading loading-spinner loading-sm"></span>
                ) : (
                  'Find matches'
                )}
              </button>
            </form>
          </div>
        )}
      </div>

      <div className="flex items-center gap-2 py-2">
        <div className="flex-1 h-px bg-scanner"></div>
        <div className="flex items-center gap-1">
          <div className="w-1 h-1 rounded-full bg-cyan-500/40"></div>
          <span className="text-[8px] font-mono text-scanner-dim/40 tracking-widest">RESULTS</span>
          <div className="w-1 h-1 rounded-full bg-cyan-500/40"></div>
        </div>
        <div className="flex-1 h-px bg-scanner"></div>
      </div>

      <div aria-busy={isFetching && searched}>
        {isFetching && searched && cards.length === 0 && (
          <div className="scanner-loading-status">
            <div className="scanner-loader">
              <div className="scanner-loader-ring"></div>
              <div className="scanner-loader-ring"></div>
              <div className="scanner-loader-ring"></div>
              <div className="scanner-loader-core"></div>
            </div>
            <span className="scanner-loading-label">SCANNING DATABASE</span>
          </div>
        )}

        {searched && cards.length > 0 && (
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-3">
            {cards.map((card, i) => (
              <Card key={card.id || i} card={card} />
            ))}
          </div>
        )}

        {!isFetching && searched && cards.length === 0 && (
          <div role="alert" className="scanner-card-frame rounded-lg bg-scanner-panel border border-scanner p-6">
            <div className="flex flex-col items-center gap-3">
              <div className="flex gap-1">
                <div className="w-1 h-4 bg-cyan-500/30 rounded signal-bar"></div>
                <div className="w-1 h-4 bg-cyan-500/30 rounded signal-bar"></div>
                <div className="w-1 h-4 bg-cyan-500/30 rounded signal-bar"></div>
                <div className="w-1 h-4 bg-cyan-500/30 rounded signal-bar"></div>
              </div>
              <span className="text-sm font-mono text-scanner-dim/60">NO ENTRIES FOUND</span>
              <span className="text-xs font-mono text-scanner-dim/40">Adjust search parameters and retry</span>
              <button
                className="btn btn-sm bg-cyan-500/10 border border-cyan-500/30 text-cyan-600 dark:text-cyan-400 hover:bg-cyan-500/20 font-mono text-xs"
                onClick={clearSearch}
              >
                RESET QUERY
              </button>
            </div>
          </div>
        )}
      </div>

      <div ref={scrollTrigger} className="h-8 flex items-center justify-center">
        {isFetchingNextPage && (
          <div className="scanner-loading-more">
            <div className="scanner-data-stream">
              {Array.from({ length: 8 }).map((_, i) => (
                <div key={i} className="scanner-data-bar"></div>
              ))}
            </div>
            <span className="scanner-loading-text">LOADING MORE...</span>
          </div>
        )}
      </div>

      {!hasNextPage && cards.length > 0 && (
        <div className="flex flex-col items-center gap-2 py-4">
          <div className="flex items-center gap-2">
            <div className="w-1 h-1 rounded-full bg-cyan-500/40"></div>
            <span className="text-xs font-mono text-scanner-dim/40">END OF RESULTS</span>
            <div className="w-1 h-1 rounded-full bg-cyan-500/40"></div>
          </div>
          <span className="text-[10px] font-mono text-scanner-dim/30">
            {cards.length} OF {totalResults} RECORDS LOADED
          </span>
        </div>
      )}
    </>
  );
}
